### ISSUE TITLE
Bluetooth Connection Error

### ISSUE THREAD

**Issue by JarvisSagar** [blueman-project/blueman#1135]
when i try to connect my bluetooth speaker , it preview a error " Connection failed protocol is not available error "
  HOW TO SOLVE THIS ERROR ???
![Screenshot at 2019-10-31 07-26-24](https://user-images.githubusercontent.com/35000232/67955419-97efca80-fc18-11e9-8568-6a15c9f6e61e.png)

**Comment by infirit** [comment]
The Bluetooth subsystem BlueZ by itself does not handle audio. It instead relies on others to register with it if they can handle things like audio. "Protocol not available" indicates nothing registered with BlueZ to handle audio. Typically this is done by PulseAudio and its Bluetooth plugin. So install PulseAudio with the necessary Bluetooth support and you should be good.

**Comment by kavyaanar** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=247892
add a2dp profile to bluealsa.service
 ( --profile=a2dp-sink)
this will resolve the protocol error

**Comment by xanda-escuyer** [comment]
> @infirit and @https://github.com/JarvisSagar
> 
> https://www.raspberrypi.org/forums/viewtopic.php?t=247892 add a2dp profile to bluealsa.service ( --profile=a2dp-sink) this will resolve the protocol error

Even though this issue is closed, it seems appropriate to confirm this solution It worked for us.
That said, it seems somewhat pedestrian that such efforts are required to get such a basic function to work; if this falls into the remit of the project then perhaps it can be included in future releases?

Debian GNU/Linux 11 (bullseye) 64-bit
GNOME 3.38.5 + Wayland

**Comment by infirit** [comment]
> That said, it seems somewhat pedestrian that such efforts are required to get such a basic function to work; if this falls into the remit of the project then perhaps it can be included in future releases?

You'd have to raise this with your disteibutuon of choice.  the BlueZ project nor Blueman have any control over this.

They can choose not to include it and leave it up to the users, like debian did (or still does?).

**Comment by cschramm** [comment]
It's basically an upstream decision and the authors state that "There is no default usage". BlueALSA 4.0 actually changed the way how this is handled: Instead of enabling `a2dp-source`, `hfp-ag` and `hsp-ag` by default, the daemon now requires explicit information on which profiles to enable, to avoid confusion. At the same time, though, the default bluealsa.service started passing `a2dp-source` and `a2sp-sink`. I do not really get how that fits the "there is no default" philosophy but I think the things in questions actually work out of the box now. https://github.com/Arkq/bluez-alsa/pull/557
