### ISSUE TITLE
Misleading UI message "Failed to connect: In Progress"

### ISSUE THREAD

**Issue by zoot** [blueman-project/blueman#1292]
**blueman-applet:** 2.0.5
**BlueZ:**
**Distribution:** Ubuntu 18.04
**Desktop environment:** XFCE

When connecting a device, after a reboot, or even resuming from suspend, such as a keyboard, then accessing the context menu "recent connections", to select the device, a notification message shows with an emphasis on failure rather than notifying the user that the connection process is underway.  So, from a user perspective, one assumes there has been a failure, rather than progress waiting.

What shows:

**Failed to connect:**
_In Progress_

What should rather show:

**In Progress:**
_Waiting for successful connection_

Edit: Changed the title and accurately recorded messages, as per below.

**Comment by cschramm** [comment]
As there is no such notification from blueman, I guess you're seeing an actual error from BlueZ that tries to tell you that there's already an operation in progress and thus connecting is not possible. However, there's no such message as "connection in progress" from BlueZ either. It should probably be either just "In Progress" (device related) or "Operation already in progress" (adapter related).

If that happens every time you use recent connections, probably somehow the connection attempt is started twice. Could you please provide the blueman-applet output for that process so that we can have a look?

**Comment by zoot** [comment]
Thanks for rapidly responding @cschramm 

You're right, I was posting from (flawed) memory, sorry. Here are the screen shots. 

![blueman-applet-01](https://user-images.githubusercontent.com/15125/87403813-a0790d00-c5bd-11ea-8428-71c4085ce4c9.png)
![blueman-applet-02](https://user-images.githubusercontent.com/15125/87403820-a2db6700-c5bd-11ea-9104-4acc0064b1eb.png)

The keyboard is always on and the broadcast icon flashing when this occurs.

Your suggested alternative wording would be far better than "Failed to connect: In progress", with the emphasis switched around.

Here's the log output ...

[blueman-applet.log](https://github.com/blueman-project/blueman/files/4917611/blueman-applet.log)

**Comment by cschramm** [comment]
There does not seem to be even a single connection attempt in the log.
