### ISSUE TITLE
Bluetooth not able to find any devices and not even discoverable in UBUNTU 20.4 LTS

### ISSUE THREAD

**Issue by DEMON1234SR** [blueman-project/blueman#1502]
blueman:blueman-applet 2.1.2
BlueZ:
Distribution:ubuntu 20.4
Desktop environment:hp notebook 15
NOT VEN A SINGLE ERROR JUST WORKING AS IT SHOULD BUT DOEN'T FIND ANY DEVICES
* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by infirit** [comment]
See https://github.com/blueman-project/blueman/wiki/Troubleshooting how to help us help you.

Not finding any devices is by itself not very usef info for us. However, generally speaking a lot of problems are due to missing firmware. Check your kernel log (dmesg) and look for messages about firmware.
