### ISSUE TITLE
Can buleman automatically respond to requests from serial data devices

### ISSUE THREAD

**Issue by xiaoye-cn** [blueman-project/blueman#1557]
blueman:2.0.8-1+deb10u1
BlueZ:5.50-1.2~deb10u1+rpt2
Distribution:
Desktop environment:Raspberry Pi OS with desktop (buster-armhf)

Thank you for your contribution. buleman is great!

I use Raspberry Pi to work with Lego EV3 (a robot toy). I installed blueman on the Raspberry Pi system. blueman can be paired and connected to LEGO EV3. Appears as a serial device. When successfully connected, blueman assigns a temporary serial port to EV3, usually "rfcomm0". I write programs in python to communicate with EV3. All this is normal.

The trouble I have encountered: Every time a connection is established, I need to right-click on the buleman manager interface to establish a serial connection or disconnect the serial connection. If I initiate a connection from the EV3, it will be disconnected 3 seconds after the connection is established. That is, buleman did not respond to EV3's request to establish a connection. (In the process of using the Raspberry Pi, there is often no screen, no keyboard and mouse.) This makes it impossible for me to complete the Bluetooth connection in an environment where there is no on-screen keyboard and mouse. This is very troublesome.

my question is:
1. Can buleman automatically answer the Bluetooth request from EV3 by a method to establish a connection and create a serial port?
2. If problem 1 cannot be realized, can buleman start the Bluetooth connection with EV3 through the command line? In this way, I can make the Raspberry Pi automatically create a connection in the python program.

If I could get your help, I would be grateful!

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by cschramm** [comment]
blueman 2.2 brings an auto-connect feature that you can switch on for the serial service. blueman 2.0 cannot, no.

There is no official and stable interface to blueman but blueman-applet does expose a D-Bus method to connect services that you could use. You need the BlueZ D-Bus object path of the device, something like `/org/bluez/hci0/dev_00_00_00_00_00_00` (basically just built from the hci and the address).

dbus-send for blueman 2.2: `dbus-send --session --print-reply --dest=org.blueman.Applet /org/blueman/Applet org.blueman.Applet.ConnectService objpath:/org/bluez/hci0/dev_00_00_00_00_00_00 string:00001101-0000-1000-8000-00805f9b34fb`

I think in 2.1 the path should be `/org.blueman/applet` instead of `/org/blueman/Applet` and in 2.0 it's `/`. The method might be called `connect_service` in 2.0. It's best to just have a look e.g. with d-feet.

**Comment by xiaoye-cn** [comment]
@cschramm 
Thank you very much for your reply!
Please forgive me, my level is not high, I still can't fully understand what you mean.
However, I found an easy way.
I wrote a line of command in the terminal: sudo rfcomm listen all
After this operation, the Raspberry Pi can respond to the Bluetooth request from the Lego EV3 and establish a virtual serial port. /dev/rfcomm0.
I use rfcomm0 directly in another python program. Complete the communication.
Thank you very much for your reply.
blueman is great!
