### ISSUE TITLE
Suddenly both device and adapter button dissabled after login

### ISSUE THREAD

**Issue by stphnvijay** [blueman-project/blueman#1580]
suddenly after logout for few minutes when i login again through both device and adapter button is dissabled. So i cant able to connect my head set through bluetooth .kindly resolve this.Iam facing this issue serveral times.
<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by vibraniumdev** [comment]
I second that.

**Comment by cschramm** [comment]
Please provide the basic information asked for in the issue template.

Assuming "device and adapter button" refers to the respective items in the menu bar, the cause seems to be that no adapter is exposed by BlueZ during that period. What do you mean with logout and login? bluetoothd is typically not a user service.
