### ISSUE TITLE
Music is lagging a lot

### ISSUE THREAD

**Issue by VladBg88** [blueman-project/blueman#1692]
Hello, 

I have connected my audio system through the Bluetooth and the music is lagging so baddly. 

Can you advice me any solution of that, pease?

**Comment by cschramm** [comment]
The right people to ask is the community of the software you use to connect to Bluetooth audio devices, but in general a lag due to buffering is rather expected when streaming audio over Bluetooth. It depends on the implementation details of the receiving device but I haven't seen a Bluetooth setup where it wasn't significant.

**Comment by anjelhm** [comment]
@VladBg88 did you find any solution?
