### ISSUE TITLE
Cannot receive files: "Sending failed" on sender.

### ISSUE THREAD

**Issue by TheoCGaming** [blueman-project/blueman#1705]
blueman: 2.1.2 (Pre-installed with Zorin)
BlueZ: 5.53
Distribution: Zorin OS Lite 16.1
Desktop environment: XFCE
Device sending file: Samsung Galaxy S9+ (SM-G965U)
Android version: 10, patch 12/1/2021
Device receiving file: Dell Inspiron 3542

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

https://pastebin.com/KRyV3xTB <-- LOG

<!--

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by TheoCGaming** [comment]
#1310 needs to be pinned because I found the solution there. 

Summary: Click on the tray icon for Blueman, go to Local Services, Transfer, then check "Accept files from trusted devices". Maybe also change the directory for received files while you're at it.

**Comment by cschramm** [comment]
#1310 is a different topic. The author expected files from trusted devices to get accepted automatically which is just not the case unless you enable the mentioned option.

Your actual problem seems to be that you're not able to accept transfers manually. You might have an issue with notifications. In your setup I'd expect xfce4-notifyd to be set up and running. Is that the case?

**Comment by TheoCGaming** [comment]
As I said, I found the solution in #1310, as in that fixed it.
