### ISSUE TITLE
Error starting blueman-mechanism

### ISSUE THREAD

**Issue by byron-hawkins** [blueman-project/blueman#1754]
blueman: checkout from github, built with autoconf and no arguments
BlueZ:
```
bluez.x86_64                                       5.56-3.el8                                                  @ol8_baseos_latest 
bluez-libs.x86_64                                  5.56-3.el8                                                  @ol8_baseos_latest 
bluez-libs-devel.x86_64                            5.56-3.el8                                                  @ol8_codeready     
bluez-obexd.x86_64                                 5.56-3.el8                                                  @ol8_baseos_latest 
```
Distribution: Oracle Linux 8.6
```
# uname -a
Linux cuivre 5.4.17-2136.307.3.5.el8uek.x86_64 #2 SMP Thu May 26 18:17:42 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Desktop environment: default gnome shipped with OL 8.6

* [X] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

[blueman-applet.log](https://gist.github.com/byron-hawkins/d939087d40e7b918aeab61a4c01e5068)

**Comment by cschramm** [comment]
I guess you're having an issue with include paths. The `blueman` package and thus also the `_blueman` package seem to be installed to `/usr/local/lib/python3.6/site-packages`. The D-Bus service's `Exec` entry, probably at `/usr/share/dbus-1/system-services/org.blueman.Mechanism.service`, points to the blueman-mechanism executable and that executable has an interpreter configured in its first line. If that interpreter does not look for python packages at `/usr/local/lib/python3.6/site-packages` by default, `blueman-mechanism` will not work.

You can use `journalctl -u blueman-mechanism.service` to check the service's error.

Packagers usually configure with `--prefix=/usr` so that search paths should be fine. To use a non-default path you'd need to modify the blueman-mechanism D-Bus service configuration (e.g. adding a `PYTHONPATH` environment variable), root's configuration, Python interpreter or similar.
