### ISSUE TITLE
Show battery level as a colored bar in the systray icon

### ISSUE THREAD

**Issue by birdie-github** [blueman-project/blueman#1796]
First of all, thanks a lot for the battery plugin however in order to check the device status you need to open "Devices" which takes a lot of mouse movement and actions. Would be great if the battery level of a connected Bluetooth device were shown as a colored bar, e.g.

![battery](https://user-images.githubusercontent.com/4958603/180619954-26099b21-8000-4d64-98c8-235b3823e14c.png)

Where the bar length _and_ color indicated the battery level:
* 41-100% - green
* 21-40% - yellow
* 20% and below red.

Would be great if these numbers were configurable because my BT headphones die when reaching 20% battery level.

---

Another option would be to show battery level as [optionally colored] text.

**Comment by cschramm** [comment]
I doubt that this a good idea for two reasons:

1. There are common tools for it and blueman should not reinvent that wheel. The battery information that blueman picks up from BlueZ is also available e.g. in UPower and UPower data gets picked up e.g. by common system tray applets, usually included by default on common desktops, so it's basically already where you want it. For Xfce on Fedora, you might need to install the `xfce4-battery-plugin` package and add it to your panel.
2. Getting the UI right is difficult. Tools dedicated to displaying battery levels often fail at it and I definitely do not want to enter that room. The most fundamental question is: What happens if there's more than one device with a battery level? Common confusion is that users wonder about their displayed notebook battery level while it's actually that of a mouse or something. In the same way, you might be wondering about your headphone level while it's actually a Bluetooth mouse.
