### ISSUE TITLE
sound coming from laptop not from headset

### ISSUE THREAD

**Issue by joey101** [blueman-project/blueman#1878]
blueman:  15.28.19 
BlueZ:
Distribution: fedora 36
Desktop environment: i3-gaps windows manager

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.
* [ ] My headphones are connected but sound still comes from the laptop. I have installed pavucontrol to see and control better but to no avail it does not even detect the headphones but within the blueman-applet itself it shows connected.

<!--
https://github.com/joey101/Bug-reports/tree/main

->
![image](https://user-images.githubusercontent.com/18228691/194688570-b880eeca-0b16-4e7a-a0cd-cfc885c66916.png)

**Comment by cschramm** [comment]
As far as I know, Fedora 36 uses PipeWire. Assuming that the headphones do not provide any HID service or anything, something, most probably PipeWire, must have handled the connection. It could be possible that PipeWire does not have its pulseaudio compatibility layer installed and enabled, but I wouldn't expect pavucontrol to work at all then.

I do not have experience with PipeWire, maybe @infirit can jump in. Otherwise, the right projects to ask for help are Fedora or PipeWire.

I'd check PipeWire's logs for the connection and probably there's a way to enable debug logging to get more.
