### ISSUE TITLE
Logitech Mouse M555b constantly disconnects

### ISSUE THREAD

**Issue by DD8372812** [blueman-project/blueman#2021]
blueman: 2.3.5
bluez: 5.6.4
Distribution: Linux MInt 21.1 based on Ubuntu 22.04 LTS
Desktop environment: Cinnamon

Hello,
my always (and on Windows still) working mouse Logitech M555b stopped working under Linux Mint 21.1. It constantly disconnects after connect. Repairing doesn't solve the problem. Other devices work. I read Linux Mint 21.1 switched from Blueberry to blueman in 21.1.

These are the syslog logs produced:
```
bluetoothd[995]: profiles/input/server.c:connect_event_cb() Refusing input device connect: No such file or directory (2)
bluetoothd[995]: profiles/input/server.c:confirm_event_cb() Refusing connection from "MAC" : unknown device
```

If you think it should be reported on other projects like Linux Mint or bluez please let me know.

**Comment by cschramm** [comment]
The first error message basically means that there is an incoming connection from the device but it's not known to have a HID service. The Internets have some rather dated and bizarre hits for it but I did not see anything really interesting.

Best project to address is probably BlueZ. You might get something fixed by wiping out some state from `/var/lib/bluetooth` (while bluetoothd is not running). However, if I get you right, the system is a fresh installation and the device never worked there, right? It's probably not just related to state then...
