### ISSUE TITLE
Newly paired BT headsets cannot pair because pin required

### ISSUE THREAD

**Issue by CodyTVWeber** [blueman-project/blueman#2033]
blueman: 2.2.4-1
BlueZ: 5.64-0ubuntu1pop1~1674313994~22.04~579884f
Distribution: Pop!_OS 22.04 jammy (x86-64)
Desktop environment: Cinnamon 5.2.7

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

<!--

![Screenshot from 2023-02-24 08-58-25](https://user-images.githubusercontent.com/120526887/221210699-16d70775-7ea7-4bfe-94ef-5320047649d7.png)

ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

->

**Comment by CodyTVWeber** [comment]
![Screenshot from 2023-02-24 08-58-25](https://user-images.githubusercontent.com/120526887/221213361-215badc8-22d2-467f-9377-68aa575efb00.png)

**Comment by CodyTVWeber** [comment]
If I switch my DE to Pop, it works without the PIN.  But if I switch my DE back to Cinnamon, it requires a pin for new device.

**Comment by cschramm** [comment]
I assume by "Pop" you mean Gnome, Pop's default DE, and thus use gnome-bluetooth instead of blueman there.

You should be able to see the agent requests from BlueZ to either blueman or gnome-bluetooth with something like
```
sudo dbus-monitor --system interface=org.bluez.Agent1
```
I'd expect no difference there, but gnome-bluetooth might be doing something fancy in response. Filtering the replies is not that easy, but
```
sudo dbus-monitor --system interface=org.bluez.Agent1 type=method_return
```
should make *all* method returns visible along the method calls for the interface and the correct one's `reply_serial` will match the call's `serial`. Curious what gnome-bluetooth does.

**Comment by infirit** [comment]
gnome-bluetooth uses connect and trust. Would be interesting to see if you pair and then connect in blueman or just click connect.
