### ISSUE TITLE
stuttery sound when connecting Samsung smartphones via bluetooth to transmit sound on a laptop via smartphones

### ISSUE THREAD

**Issue by siwy666** [blueman-project/blueman#2216]
blueman:2.3.5
BlueZ:5.70
Distribution:archcraft
Desktop environment:openbox

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by cschramm** [comment]
Might be an issue of your sound server (typically pulseaudio or PipeWire). I'd try a different one to see if that's the case.

**Comment by siwy666** [comment]
When i change  in samsung galaxy a 12 in developer options ( i turn off hd audio, i set coded audio bluetooth to SBC and everything change to default  in sound bluetooth) everything works prefectly.

**Comment by infirit** [comment]
Just speculating but..

The SBC codec bandwith requirement is about 320kb/s max. Compare that to something like LDAC that maxes out at 900kb/s. Aptx is more reasonable depending on the the version which is between 380 and 580kb/s.

If switching to SBC fixes the stuttering it may be because of the higher bandwith requirements. However this shouldn't be a problem with modern hardware and Bluetooth versions. Unless there is radio interference from WiFi, distance or walls.

**Comment by siwy666** [comment]
When I turn off HD Sound in Developer options ant other bluetooth settings i set in default sound from Samsung A12 is perfect.
