### ISSUE TITLE
Pls help me with this Bluetooth modem

### ISSUE THREAD

**Issue by kskarthik** [blueman-project/blueman#480]
I am having problem with this modem since a long time (years). The modem is working but i am unable to connect it :cry: 
Please help me out 
![screenshot from 2016-03-09 19 21 18](https://cloud.githubusercontent.com/assets/11899221/13637197/0c68e9de-e62c-11e5-850c-40e8234cf57b.png)

**Comment by infirit** [comment]
The adapter appears to be supported in bluez but from what I can gather it has issues with older kernels and/or bluez versions. You can do a search on the ubuntu forums to see many people with problems and this device, apparently it got solved in an updated bluez version (4.101?). Blueman relies on bluez working properly and if the problem is there there is little we can do.

Also, if you feel there is a real issue with blueman please have a look at our [trouble shooting](https://github.com/blueman-project/blueman/wiki/Troubleshooting) page how to ask for support.
