### ISSUE TITLE
Active Icon Appears Twice

### ISSUE THREAD

**Issue by yodaldevoid** [blueman-project/blueman#667]
I recently did a distro update for Ubuntu and after updating Blueman's tray icon was doubled. It is not a second icon next to the other, but rather the icon has two bluetooth symbols side by side. The attached picture should show what I mean. ![blueman_double_icon](https://cloud.githubusercontent.com/assets/1204409/23342731/9486b2fc-fc2d-11e6-9f1a-7d005b2f7126.png) All other icons appear as expected. I am running Ubuntu 16.10 with i3 as my window manager and i3status as my status bar.

**Comment by infirit** [comment]
I'll setup a 16.10 vm and see if I can reproduce what iso did you use as base, unity, gnome, kde? in the mean time can you go into bluemans plugin dialog and disable the AppIndicator plugin and report if one of the two goes away.

**Comment by yodaldevoid** [comment]
I believe there has been some misunderstanding. There is only one icon object, but the icon image has two Bluetooth symbols side by side. I have seen this issue on unity and i3.

**Comment by infirit** [comment]
I understand. Blueman comes with two plugins for this icon. One that uses the old tray icon functionality the other is using the app indicator. Currently the former is mandatory the latter is not. It may be that for some reason this causes an issue and as it is a easy thing to try until I have vm setup :-).

Also of note is that blueman does not provide a black icon only blue ones. Can you try changing your icon theme to, lets say the default gtk one (adwaita) so that the blue one like [1] shows? Does it still look the same?

https://github.com/blueman-project/blueman/blob/master/data/icons/main_icon/hicolor_apps_128x128_blueman.png

**Comment by yodaldevoid** [comment]
When I turn off the AppIndicator plugin nothing changes for my current i3 setup. It seems that Ubuntu was setting the icon them to ubuntu-mono-dark without me realizing, and when forced to Adwaita the default blue icon appears.

**Comment by yodaldevoid** [comment]
It appears as if Ubuntu supplies a SVG for the bluetooth-active icon that is also used for the Blueman tray icon. It makes me wonder if SVGs are not being handled correctly somewhere in the pipeline.

**Comment by infirit** [comment]
Just to be clear, with the blue icon it is show correctly?

The thing is we do not force any format or size. We just tell the implementation (tray/indicator) the icon name to use and leave it to handle the rest. Then the implementation looks up the icon in the currently active icon theme. The standard icon we set is ``blueman-tray`` and if the ShowConnected plugin is enabled __and__ we have active connection(s) we use ``blueman-active``.

I now have i3 running with i3bar for the tray. I have trouble having it show icons of the tray, can you post your ``bar { bla bla }`` config so I can copy it?

**Comment by yodaldevoid** [comment]
Yes, the blue icon is correctly showing itself. Make sure that your primary monitor is actually set as primary under xrandr or else the icon tray may not show up. [docs](https://i3wm.org/docs/userguide.html#_tray_output)

```
bar {
        status_command i3status
        tray_output primary
        position top
}
```

**Comment by yodaldevoid** [comment]
This is looking more and more like a problem on i3's side. I have just booted into a live CD of Ubuntu 16.10, installed Blueman, and don't see the problem in Unity (though I was fairly certain that I had seen it before.)

**Comment by infirit** [comment]
Maybe, or ubuntu 16.10s icon for blueman. Unfortunately ubuntu 16.10 painfully to work with (slow mostly) in VirtualBox so getting things done is hard. I'll continue tomorrow to get the icons to show in i3bar.

**Comment by infirit** [comment]
Ok, so the lack of icons is due to Gtk3 bugs and had to increase the font size. Now I have tray icons \o/.

But then I do not see the same problem you are.. The vm is based on a standard ubuntu desktop cd and then using the stable repo from https://i3wm.org/docs/repositories.html. 

When no devices are connected I see a single black icon and when connected the blueman-active (blue and green). So indeed this sounds like an issue with your install or i3bar.

**Comment by yodaldevoid** [comment]
With some messing around with the font size for the bar's font I get the icon to display correctly. It indeed looks like it is a problem with i3bar, or rather cairo which I believe they use for rendering. For future reference a minimum font size of 12 was required for the icon to display correctly. I am going to close this as it is not Blueman's fault/issue.

**Comment by infirit** [comment]
Or it is Gtk not able to handle sizes smaller than 12. I have seen icon size problems and gtk status icon mentioned in several posts and bug reports on the interwebs. But in any case I do agree that from bluemans point of view there is not much we can do.
