### ISSUE TITLE
Unable to connect to bluetooth audio sync. "Connection failed. Did not recieve a reply". 

### ISSUE THREAD

**Issue by groceryheist** [blueman-project/blueman#683]
blueman:2.0.4
BlueZ:5.43
Distribution:Debian Sid
Desktop: XFCE

https://gist.github.com/57a405f92aadab18b8bdaf92eb75df88#file-log-L155 connect to audio sink (D2DP)
https://gist.github.com/57a405f92aadab18b8bdaf92eb75df88#file-log-L176 the error was "resource temporarily unavailable"
https://gist.github.com/57a405f92aadab18b8bdaf92eb75df88#file-log-L177 open devices
https://gist.github.com/57a405f92aadab18b8bdaf92eb75df88#file-log-L178 try connecting to A2DP again
https://gist.github.com/57a405f92aadab18b8bdaf92eb75df88#file-log-L194 the error was "connection failed did not recieve a reply. ..."

I have checked that pulseaudio has loaded modules  bluez5-discover, bluetooth-discover, bluetooth-policy.

**Comment by infirit** [comment]
These errors indicate that the adapter has problems communicating with the device. This part is handled by the BlueZ layer and there is likely not much we can do here. However..

Connecting to an audio profile under bluez5 can be done from the command line with ``bluetoothctl``. Can you attempt to connect using this? If you need to pair you will want to issue ``agent on`` from withing ``bluetoothctl``. If that also does not work the problem is likely in BlueZ.
